name: Deploy Development
run-name: Deploy to ECS (Development) - ${{ github.ref_name }}


on:
  push:
    branches: ["v4-dev"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  deploy-infra:
    uses: ./.github/workflows/infra-provision.yml
    with:
      application: js
      environment_name: development
    secrets: inherit

  deploy-app:
    needs: deploy-infra
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      application: js
      environment_name: development
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}